### ISSUE TITLE
API fails to fetch data if period is too long

### ISSUE THREAD

**Issue by leroquan** [eawag-surface-waters-research/alplakes-react#46] opened 2024-07-01 14:29 UTC
Example : https://alplakes-api.eawag.ch/simulations/point/delft3d-flow/geneva/202305010000/202409010000/1/46.5/6.67

Error : HTTPError: 502 Server Error: Bad Gateway for url: https://alplakes-api.eawag.ch/simulations/point/delft3d-flow/geneva/202305150000/202409010000/1/46.5/6.67

The error doesn't happen all the time. Sometimes it works but then the the data only goes up to 2024-08-07 instead of 2024-09-01.

**Comment by JamesRunnalls** [comment] 2024-08-08 08:18
Closing as a duplicate of the issue here https://github.com/eawag-surface-waters-research/alplakes-fastapi/issues/7

**Closed by JamesRunnalls** 2024-08-08 08:18 UTC
